version: '2'
plugins:
  eslint:
    enabled: true
exclude_patterns:
- "src/config/"
- "src/sequelize/models/"
- "src/sequelize/migrations/"
- "src/sequelize/seeders/"
- "**/node_modules/"
- "test/**/*.js"
- "src/middleware/search.js"
- "src/helpers/user/*.js"
- "src/helpers/article/*.js"
- "src/helpers/comment/*.js"
- "src/helpers/validationSchemas.js"
- "src/middleware/shareArticle.js"
- "src/helpers/SocketIO.js"